### ISSUE TITLE
[PE-D] Editing recipe in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-1/tp#161]
Explanation should be clearer in that when editing a certain component like with the field flag -i, all the existing ingredients will be overwritten and replaced with the new ingredients. The explanations are brief.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: driip-ddrop/ped#6

**Comment by alissayarmantho** [comment]
Not sure why it is left open when the PR is merged. Closing by #238
