### ISSUE TITLE
[PE-D] Suggestion - commands are too long

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-1/tp#163]
It was rather inconvenient to have to type both commands like add recipe and add ingredients. Perhaps would be better to have shorter commands.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: driip-ddrop/ped#7

**Comment by alissayarmantho** [comment]
Thank you for the feedback! Unfortunately, we are not allowed to add any more features. If there are any more iterations, we can do this for sure!
