### ISSUE TITLE
[PE-D] Incomplete ingredient tracker feature

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-1/tp#173]
I think that your app solves a real problem being a student that lives in a RC! However I feel like the ingredient tracker feature is kind of incomplete, I personally fill it would be good to include a field option for ingredients to indicate which ingredient belongs to which individual in the shared place. As one pertinent problem I faced is that people might sometimes use ingredients that do not belong to them. After implementing this, you could also potentially implement the cook recipe feature to only ensure that the person is cooking using ingredients belonging to the correct individual.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: KT27Learn/ped#7

**Comment by NayLin-H99** [comment]
Not really a bug, but thanks for the suggestion. We aren't allowed to add more features so 😞
