### ISSUE TITLE
[PE-D] Find command is not case sensitive but add command is case sensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-1/tp#174]
There is no remark in the UG stating that this is meant to be the case.

Being permitted to add same name ingredients with different case, but seeing names of all cases when using the find command is not consistent.

Not sure if this is a bug or if it is meant to be this way.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: ramapriyan912001/ped#9

**Comment by rootkie** [comment]
This has the same root cause as #188, closed for duplicate
