### ISSUE TITLE
[PE-D] Case sensitivity - Cook Recipe

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-1/tp#185]
For ingredients, it could be in all small letter but the recipe includes capital letters for the same ingredient. When entering the command `cook recipe` is it supposed to be case sensitive? For find it is case insensitive and user could expect this to be case insensitive as well.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: driip-ddrop/ped#14

**Comment by rootkie** [comment]
This has the same root cause as #188, closed for duplicate
