### ISSUE TITLE
[PE-D] Weird numbers can be added for add ingredient 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-1/tp#187]
Would suggest that for quantity without units, could allow just whole numbers or 1.5, 2.5 and etc. only to be accepted. Weird number like 3.45678 can be accepted currently.
![Screenshot 2021-10-29 at 5.37.31 PM.png](https://raw.githubusercontent.com/LiuZhi1an/ped/main/files/1a9db64c-f047-4f14-966b-19a6776c2791.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: LiuZhi1an/ped#11

**Comment by NayLin-H99** [comment]
This was initially left as such because restricting it too much might affect certain use cases. Perhaps a rounding system should be added.

**Comment by rootkie** [comment]
This is not really a bug. It doesn't affect user experience if they want to input value of pi into the quantity.
