### ISSUE TITLE
[PE-D] Add on to the issue Suggestion - message when listing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-1/tp#189]
I realised that your app sorts ingredients based on expiration date. Maybe it would be good to add this into the UG.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: driip-ddrop/ped#16

**Comment by alissayarmantho** [comment]
Not sure why it is left open when the PR is merged. Closing by #238
