### ISSUE TITLE
[PE-D] Inconsistent Tag color

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-1/tp#191]
`cook recipe <index>` would consume ingredients. The tag color of recipe should be blue when it is able to cook, and red when it is not able to cook. But after finishing the ingredients, the color of the tag stays blue. After exiting the app and relaunching, the tag turns to red.

![Screenshot from 2021-10-29 21-47-28.png](https://raw.githubusercontent.com/SpdPnd98/ped/main/files/67c75b90-189d-4d25-af22-cac86d958cd9.png)
![Screenshot from 2021-10-29 21-48-06.png](https://raw.githubusercontent.com/SpdPnd98/ped/main/files/9826f969-3972-4edc-9b37-ce4f7c4fd205.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: SpdPnd98/ped#3

**Comment by rootkie** [comment]
Duplicate issue to #181. Closed.
