### ISSUE TITLE
[PE-D] List Recipe stays on ingredients tab

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-1/tp#192]
When entering listing of ingredients or recipe, user will need to manually click on the tab to view the result of `list`. Eg, when the user is at the `Recipe` page, and types `list ingredient`, they will need to manually navigate to the page to verify it is correct. 
![Screenshot from 2021-10-29 21-52-10.png](https://raw.githubusercontent.com/SpdPnd98/ped/main/files/c9d73d28-e456-4de0-a2a1-827aad36b0f1.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: SpdPnd98/ped#4

**Comment by alissayarmantho** [comment]
Duplicate of #177
