### ISSUE TITLE
[PE-D] More informative error messages

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W11-1/tp#193]
For this example, users entered:
```
add ingredient -n test -q 200000000000g -e 00-00-0000
```
But users do not know what information is incorrect.
![Screenshot from 2021-10-29 21-59-09.png](https://raw.githubusercontent.com/SpdPnd98/ped/main/files/d4a1c99b-2d2c-4e76-be85-e250a2e1696c.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: SpdPnd98/ped#5

**Comment by rebeccacxy** [comment]
Weirdly when run normally (not the jar itself), it produces:
`Caused by: java.time.format.DateTimeParseException: Text '00-00-0000' could not be parsed: Invalid value for YearOfEra (valid values 1 - 999999999/1000000000): 0`

**Comment by rootkie** [comment]
The root cause of this is due to incorrect expiry date parsing.
