### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by rebeccacxy** [AY2122S1-CS2103T-W11-1/tp#9]
1. Add UI mockup of the intended final product. Image of the UI should be `docs/images/Ui.png`. Ensure new image is roughly the same `height x width` proportions as the original one.
2. Update all contents to match your own project
3. Update the link of the GitHub Actions build status badge so that it reflects the build status of team repo
4. Acknowledge the original source of the code e.g.,
`This project is based on the AddressBook-Level3 project created by the [SE-EDU initiative](https://se-education.org).`

**Comment by rootkie** [comment]
Also need to change
```markdown
[![CI Status](https://github.com/se-edu/addressbook-level3/workflows/Java%20CI/badge.svg)](https://github.com/se-edu/addressbook-level3/actions)
```
to
```markdown
[![CI Status](https://github.com/AY2122S1-CS2103T-W11-1/tp/workflows/Java%20CI/badge.svg)](https://github.com/AY2122S1-CS2103T-W11-1/tp/actions)
```
